# Generated by Django 3.1.5 on 2021-02-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_maintance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintance',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
