# Generated by Django 3.1.5 on 2021-02-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0008_auto_20210208_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=25)),
                ('discount_type', models.IntegerField(choices=[(1, 'Pecentage'), (2, 'Flat')], verbose_name='Discount Type')),
                ('total_discount', models.PositiveSmallIntegerField()),
                ('offer_type', models.CharField(choices=[('Site', 'Site offer - available to all users'), ('Voucher', 'Voucher offer - only available after entering the appropriate voucher code'), ('User', 'User offer - available to certain types of user'), ('Session', 'Session offer - temporary offer, available for a user for the duration of their session')], default='Site', max_length=128, verbose_name='Type')),
                ('min_order', models.PositiveIntegerField(blank=True, null=True)),
                ('applicable_on', models.PositiveSmallIntegerField(choices=[(1, 'MRP'), (2, 'Selling Price')], verbose_name='Applicable on Price')),
                ('max_user_applications', models.PositiveIntegerField(blank=True, help_text='The number of times a single user can use this offer', null=True, verbose_name='Max user applications')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('start_datetime', models.DateField(blank=True, help_text='Offers are active from the start date. Leave this empty if the offer has no start date.', null=True, verbose_name='Start date')),
                ('end_datetime', models.DateField(blank=True, help_text='Offers are active until the end date. Leave this empty if the offer has no expiry date.', null=True, verbose_name='End date')),
                ('on_category', models.ManyToManyField(blank=True, help_text='Select category to avail. Leave this empty to select all category.', to='products.Category')),
            ],
        ),
    ]
