# Generated by Django 3.1.5 on 2021-02-03 20:22

import admins.models
import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=admins.models.directory_path)),
                ('caption', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='caption')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Display Order')),
            ],
        ),
    ]
