# Generated by Django 3.1.5 on 2021-02-08 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_availableaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableaddress',
            name='pincode',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='Pincode number must be 6 digits long.', regex='^\\d{6}$')]),
        ),
    ]
