# Generated by Django 3.1.5 on 2021-02-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20210208_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Display Order'),
        ),
    ]
