# Generated by Django 3.1.5 on 2021-01-22 07:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^(\\+\\d{1,3})?,?\\s?\\d{10}')])),
                ('pincode', models.PositiveIntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Pincode number must be 6 digits long.', regex='^(\\+\\d{1,3})?,?\\s?\\d{6}')])),
                ('house', models.CharField(max_length=255, verbose_name='Flat, House no., Building')),
                ('area', models.CharField(max_length=255, verbose_name='Area, Street, Village')),
                ('city', models.CharField(max_length=55)),
                ('state', models.CharField(max_length=40)),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Address Description')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
