# Generated by Django 3.1.5 on 2021-01-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210127_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='tid',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
