# Generated by Django 3.1.5 on 2021-01-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210128_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='expected_dt',
            field=models.DateField(null=True, verbose_name='Expected Delivery Date'),
        ),
    ]
