# Generated by Django 3.1.5 on 2021-02-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_expected_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Pending'), (2, 'Confirm'), (3, 'Rejected'), (4, 'Completed')], default=1, verbose_name='Order Status'),
        ),
    ]
