# Generated by Django 3.1.5 on 2021-02-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210203_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Processing'), (3, 'Shipped'), (4, 'Delivered'), (5, 'Rejected'), (6, 'Canceled')], default=0, verbose_name='Order Status'),
        ),
    ]
