# Generated by Django 3.1.5 on 2021-02-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210212_1307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderstatus',
            unique_together={('order', 'status')},
        ),
    ]
