# Generated by Django 3.1.5 on 2021-01-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20210121_1835'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='_(This proudct already exists in cart)'),
        ),
    ]
