# Generated by Django 3.1.5 on 2021-01-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210120_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.FloatField(default=400),
            preserve_default=False,
        ),
    ]
