# Generated by Django 3.1.5 on 2021-01-30 05:18

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210120_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True, verbose_name='Description'),
        ),
    ]
