# Generated by Django 3.1.5 on 2021-02-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_stockrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockrecord',
            name='num_allocated',
            field=models.IntegerField(default=0, verbose_name='Number allocated'),
        ),
        migrations.AlterField(
            model_name='stockrecord',
            name='num_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Number in stock'),
            preserve_default=False,
        ),
    ]
