# Generated by Django 3.1.5 on 2021-03-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210208_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_boolean',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_date',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_datetime',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_float',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_integer',
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value_text',
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
