# Generated by Django 3.1.5 on 2021-03-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210304_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='value',
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_boolean',
            field=models.BooleanField(db_index=True, null=True, verbose_name='Boolean'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='DateTime'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_float',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Float'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_integer',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Integer'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
