# Generated by Django 3.1.5 on 2021-05-12 10:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210304_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Discounted Price')),
                ('fdate', models.DateField(default=datetime.date.today, verbose_name='From Date')),
                ('ldate', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
